### ISSUE TITLE
Looks like some part of codes missing 

### ISSUE THREAD

**Issue by zuiluo1116** [dpcook/thebaud_lung_BPD#1]
Processing RMD end with “saveRDS(seurat, file="../output/merged_data_unfiltered.rds")”, and DSA RMD start with "seurat <- readRDS("../output/merged_data_filtered.rds")".
Is there something I miss?
Probably with cell cycle scoring and cell filtering?

**Comment by dpcook** [comment]
Really sorry about that! I had missed an upload on a second processing script. [See here](https://github.com/dpcook/thebaud_lung_BPD/blob/main/processing_2.Rmd).

The key filtering is removing cells that were not successfully annotated as singlets based on MULTI-seq barcodes (ie. negatives and doublets). The new script removes them and then does some further processing (cell cycle regression & integration w/ harmony).

Fwiw, I have a google drive with .Rds files containing all the seurat objects we used, including the cell subsets. Can access [here](https://drive.google.com/drive/folders/1xg94fw-hLNgKCad96ogS6eFUu0CL9_u8?usp=sharing)
